language: python
python:
  - "3.7"

stages:
  - deploy

env:
  - DOCKER_COMPOSE_VERSON=1.4.2

jobs:
  include:
    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: ${HEROKU_KEY}
        app: alohomora-bot
        on:
          repo: Alohomora-team/2019.2-AlohomoraBot
          branch: devel