language: python
python:
  - "3.7"

stages:
  - code_style
  - deploy

env:
  - DOCKER_COMPOSE_VERSON=1.4.2

jobs:
  include:
    - stage: code_style
      script:
        - docker-compose run lint

    # Deploy HMG
    - stage: deploy
      if: (branch = testedeploybot) AND (type != pull_request)
      install: skip
      script: skip
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: ${HEROKU_KEY}
        app: alohomora-bot-hmg
        on:
          repo: Alohomora-team/2019.2-AlohomoraBot
          branch: testedeploybot

    #Deploy PROD
    - stage: deploy
      if: (branch = master) AND (type != pull_request)
      install: skip
      script: skip
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: ${HEROKU_KEY}
        app: alohomora-bot
        on:
          repo: Alohomora-team/2019.2-AlohomoraBot
          branch: master