language: python
python:
  - "3.7"

stages:
  - code_quality_tests

env:
  - DOCKER_COMPOSE_VERSON=1.4.2

jobs:
  include:
    - stage: code_quality_tests
      script:
        - docker-compose run lint