version: "3.7"

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    volumes:
    - "./bot:/home"
    depends_on:
    - api

  api:
    image: alohomorateam/api:devel
    ports:
    - "8000:8000"
    env_file: ".env"
    depends_on:
    - db

  db:
    image: postgres:11.5-alpine
    env_file: ".env"

  lint:
    # directory with code
    command: "bot"
    build:
      context: .
      dockerfile: docker/lint/Dockerfile
    # The volume with pylintrc configuration
    volumes:
    - "./:/home"
